export const FETCH_POKEDEX_REQUEST = 'FETCH_POKEDEX_REQUEST'
export const FETCH_POKEDEX_SUCCESS = 'FETCH_POKEDEX_SUCCESS'
export const FETCH_POKEDEX_FAILURE = 'FETCH_POKEDEX_FAILURE'
export const FETCH_POKEDEX_CLEAR = 'FETCH_POKEDEX_CLEAR'
